using System.Text;
using AiReliabilityEngineering.Core.Agents;
using AiReliabilityEngineering.Core.Artifacts;
using AiReliabilityEngineering.Orchestration.Logging;

namespace AiReliabilityEngineering.Orchestration.Agents;

public sealed class FakeRequirementsAgent(IRunLogger logger) : IAgent
{
    public string Name => "RequirementsAgent";

    public async Task<AgentResult> ExecuteAsync(AgentContext context, CancellationToken cancellationToken)
    {
        await logger.InfoAsync($"{Name} started", cancellationToken);
        var relativePath = "artifacts/specification.json";
        var path = Path.Combine(context.Run.Paths.ArtifactsDirectory, "specification.json");
        await File.WriteAllTextAsync(path, """
            {
              "name": "placeholder-project",
              "summary": "Generated by fake requirements agent.",
              "requirements": [
                "Read initial idea file",
                "Generate placeholder workflow artifacts"
              ]
            }
            """, Encoding.UTF8, cancellationToken);
        await logger.InfoAsync($"{Name} completed", cancellationToken);
        return AgentResult.Success("Requirements placeholder generated.", [new ArtifactRef(ArtifactType.Specification, relativePath, "Placeholder specification")]);
    }
}

public sealed class FakeDocumentationAgent(IRunLogger logger) : IAgent
{
    public string Name => "DocumentationAgent";

    public async Task<AgentResult> ExecuteAsync(AgentContext context, CancellationToken cancellationToken)
    {
        await logger.InfoAsync($"{Name} started", cancellationToken);
        var readmePath = Path.Combine(context.Run.Paths.ArtifactsDirectory, "README.md");
        var planPath = Path.Combine(context.Run.Paths.ArtifactsDirectory, "PLAN.md");
        await File.WriteAllTextAsync(readmePath, "# Placeholder README\n\nGenerated by the fake documentation agent.\n", Encoding.UTF8, cancellationToken);
        await File.WriteAllTextAsync(planPath, "# Placeholder Plan\n\nThis is a placeholder plan generated by the fake documentation agent.\n", Encoding.UTF8, cancellationToken);
        await logger.InfoAsync($"{Name} completed", cancellationToken);
        return AgentResult.Success(
            "Documentation placeholders generated.",
            [
                new ArtifactRef(ArtifactType.Documentation, "artifacts/README.md", "Placeholder README"),
                new ArtifactRef(ArtifactType.Plan, "artifacts/PLAN.md", "Placeholder plan")
            ]);
    }
}

public sealed class FakePlannerAgent(IRunLogger logger) : IAgent
{
    public string Name => "PlannerAgent";

    public async Task<AgentResult> ExecuteAsync(AgentContext context, CancellationToken cancellationToken)
    {
        await logger.InfoAsync($"{Name} started", cancellationToken);
        var path = Path.Combine(context.Run.Paths.ArtifactsDirectory, "tasks.json");
        await File.WriteAllTextAsync(path, """
            [
              {
                "id": "T001",
                "title": "Implement skeleton",
                "status": "placeholder"
              }
            ]
            """, Encoding.UTF8, cancellationToken);
        await logger.InfoAsync($"{Name} completed", cancellationToken);
        return AgentResult.Success("Task placeholders generated.", [new ArtifactRef(ArtifactType.Tasks, "artifacts/tasks.json", "Placeholder tasks")]);
    }
}

public sealed class FakeCodeAgent(IRunLogger logger) : IAgent
{
    public string Name => "CodeAgent";

    public async Task<AgentResult> ExecuteAsync(AgentContext context, CancellationToken cancellationToken)
    {
        await logger.InfoAsync($"{Name} started", cancellationToken);
        var srcDirectory = Path.Combine(context.Run.Paths.WorkspaceDirectory, "src");
        Directory.CreateDirectory(srcDirectory);
        await File.WriteAllTextAsync(Path.Combine(context.Run.Paths.WorkspaceDirectory, "README.md"), "# Workspace\n\nGenerated by the fake code agent.\n", Encoding.UTF8, cancellationToken);
        await File.WriteAllTextAsync(Path.Combine(srcDirectory, "placeholder.txt"), "Placeholder source file generated by the fake code agent.\n", Encoding.UTF8, cancellationToken);
        await logger.InfoAsync($"{Name} completed", cancellationToken);
        return AgentResult.Success(
            "Workspace placeholders generated.",
            [
                new ArtifactRef(ArtifactType.Code, "workspace/README.md", "Workspace README"),
                new ArtifactRef(ArtifactType.Code, "workspace/src/placeholder.txt", "Placeholder source")
            ]);
    }
}

public sealed class FakeTestAgent(IRunLogger logger) : IAgent
{
    public string Name => "TestAgent";

    public async Task<AgentResult> ExecuteAsync(AgentContext context, CancellationToken cancellationToken)
    {
        await logger.InfoAsync($"{Name} started", cancellationToken);
        var path = Path.Combine(context.Run.Paths.ReportsDirectory, "tests.md");
        await File.WriteAllTextAsync(path, "# Tests\n\nTests are simulated and passed.\n", Encoding.UTF8, cancellationToken);
        await logger.InfoAsync($"{Name} completed", cancellationToken);
        return AgentResult.Success("Simulated tests passed.", [new ArtifactRef(ArtifactType.Tests, "reports/tests.md", "Simulated test report")]);
    }
}

public sealed class FakeReviewerAgent(IRunLogger logger) : IAgent
{
    public string Name => "ReviewerAgent";

    public async Task<AgentResult> ExecuteAsync(AgentContext context, CancellationToken cancellationToken)
    {
        await logger.InfoAsync($"{Name} started", cancellationToken);
        var path = Path.Combine(context.Run.Paths.ArtifactsDirectory, "review.md");
        await File.WriteAllTextAsync(path, "# Review\n\nStatus: Passed\n\nThis is a fake review report for the first AIRE skeleton.\n", Encoding.UTF8, cancellationToken);
        await logger.InfoAsync($"{Name} completed", cancellationToken);
        return AgentResult.Success("Fake review passed.", [new ArtifactRef(ArtifactType.Review, "artifacts/review.md", "Fake review report")]);
    }
}
